service: quack-reduce-lambda
useDotenv: true

provider:
  name: aws
  architecture: arm64
  memorySize: 3008
  timeout: 600
  ecr:
    images:
      quackimageblog:
        path: ./
        platform: linux/arm64
  environment:
    S3_USER: ${env:S3_USER}
    S3_ACCESS: ${env:S3_ACCESS}
    HOME: /tmp

#custom:
#  dotenv:
#    path: ../.env
#    include:
#      - S3_USER
#      - S3_ACCESS
#      - S3_BUCKET_NAME


functions:
  duckdb:
    ephemeralStorageSize: 3008
    image:
      name: quackimageblog

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${env:S3_BUCKET_NAME}

#plugins:
#  - serverless-dotenv-plugin